<a href="https://colab.research.google.com/github/ChandeeshSG/Machine-Learning/blob/main/DAY_1_ML_(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[1,2,3]
print(a)
a.append(5)
print(a)

[1, 2, 3]
[1, 2, 3, 5]


In [ ]:
a=(11,12,13)
print(a)
b=(21,22,23)
print(b)
c=a+b
print(c)

(11, 12, 13)
(21, 22, 23)
(11, 12, 13, 21, 22, 23)


In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
a = np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
x=np.array([1,2])
y=np.array([2.0,4.0])
print(x.dtype,y.dtype)

int64 float64


In [ ]:
print(np.ones((2,4)))
print(np.zeros((2,6)))
print(np.full((2,4,8),7))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]]

 [[7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]
  [7 7 7 7 7 7 7 7]]]


In [ ]:
c=np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
d=np.linspace(0,1,num=5)
print(d)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
q=np.array([[1,2,4,5],[3,4,6,7]])
print(q[0,0:3])
print(q[0:3,1:3])     #Before comma(,) represents a ROW and after comma represents COLUMN

[1 2 4]
[[2 4]
 [4 6]]


In [ ]:
s=np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]


In [ ]:
r1=s[1, :]          # (:) prints the entire row
r2=s[1:3, :]
r3=s[[1], :]
print(r1,r1.shape)
print(r2,r2.shape)
print(r3,r3.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [11 12 13 14]] (2, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
c1=s[:,1]          #(:) prints the entire column
c2=s[:,1:3]
c3=s[:,2:3]
print(c1,c1.shape)
print(c2,c2.shape)
print(c3,c3.shape)

[ 2  6 12] (3,)
[[ 2  3]
 [ 6  7]
 [12 13]] (3, 2)
[[ 3]
 [ 7]
 [13]] (3, 1)


In [ ]:
a=np.array([[1,2,3],[4,5,6],[8,9,0],[11,12,13]])
b=np.array([0,2,1,0])                            #Act as a index for 'a'
print(a[np.arange(4),b])

[ 1  6  9 11]


In [ ]:
bool_idx=(a>2)
bool_idx
#a[a>2]

array([ 3,  4,  5,  6,  8,  9, 11, 12, 13])

In [ ]:
a=np.array([1,8,4,6,2,7,-6,3,6])
print(a)
print(np.argmax(a))             #Returns the greatest number's index
print(np.argmin(a))             #Returns the smallest number's index
print(np.argsort(a))            #Returns the index of the sorted elements from smallest to largest
print(np.argsort(a)[::-1])      #Returns the index of the sorted elements from largest to smallest
print(np.where(a>1)[0])

[ 1  8  4  6  2  7 -6  3  6]
1
6
[6 0 4 7 2 3 8 5 1]
[1 5 8 3 2 7 4 0 6]
[1 2 3 4 5 7 8]


In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])       #Add the elements in the list
print(a)
b=np.delete(a,[0,4])           #Delete the elements in the list
print(b)

[0 1 2 3 4]
[1 2 3]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[8,9,0],[11,12,13]])
print(a)
a=np.sort(a,axis=1,kind="quicksort")
b=np.sort(a,axis=0,kind="quicksort")           #axis=0 Columnwise sort,axis=1 Rowwise sort
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9  0]
 [11 12 13]]
[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [11 12 13]]
[[ 0  2  3]
 [ 1  5  6]
 [ 4  8  9]
 [11 12 13]]


In [ ]:
a=np.array([[1],[4],[8],[11]])
x=a.squeeze()
print(x)
x.shape

[ 1  4  8 11]


(4,)