<a href="https://colab.research.google.com/github/ChandeeshSG/Machine-Learning/blob/main/Neural_Network_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np

In [18]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [19]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [20]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [21]:
def derivative_sigmoid(x):
  return x*(1-x)

In [22]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [23]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))    #weights(hidden)
bh=np.random.uniform(size=(1,hidden_neurons))                #bias(hidden)
wo=np.random.uniform(size=(hidden_neurons,output_neurons))   #Weights(output)
bo=np.random.uniform(size=(1,output_neurons))                #bias(output)

In [24]:
for i in range(epoch):

  #Forward Propagation
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)

  #Backward Propagation
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr


In [25]:
output

array([[0.94969571],
       [0.07085872],
       [0.97425279]])