<a href="https://colab.research.google.com/github/ChandeeshSG/Machine-Learning/blob/main/TensorFlow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [27]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [28]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [29]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [30]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.46235833,  0.08996154,  0.07875749,  0.5663742 ,  0.4295429 ,
         0.38955832, -0.85749674,  0.5755968 , -0.7221126 , -0.08096321]],
      dtype=float32)

In [31]:
tf.nn.softmax(predictions).numpy()

array([[0.13069499, 0.0900594 , 0.08905601, 0.14502151, 0.12647578,
        0.12151846, 0.0349183 , 0.14636518, 0.03998064, 0.07590972]],
      dtype=float32)

In [32]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [33]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [34]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2900 - accuracy: 0.9162
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1394 - accuracy: 0.9587
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1059 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0875 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0749 - accuracy: 0.9770


In [35]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0761 - accuracy: 0.9767 - 534ms/epoch - 2ms/step


[0.0761299654841423, 0.9767000079154968]

In [36]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [37]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.33836870e-08, 7.08411036e-08, 3.13561782e-06, 3.08420626e-04,
        1.18016139e-10, 1.84215896e-08, 4.92799866e-13, 9.99678969e-01,
        8.91431057e-07, 8.48034233e-06],
       [1.32419609e-09, 1.06785810e-05, 9.99964476e-01, 1.95052689e-05,
        4.54904031e-11, 4.27959321e-06, 2.67376919e-07, 1.86925996e-11,
        8.69826920e-07, 9.71581824e-14],
       [1.93609910e-08, 9.98807073e-01, 1.80769013e-04, 1.78243899e-05,
        4.32075503e-05, 1.85524254e-06, 1.64321445e-05, 8.12632090e-04,
        1.19372824e-04, 7.74248008e-07],
       [9.99910235e-01, 3.42825185e-10, 1.43593354e-06, 3.19270748e-06,
        1.77627825e-07, 1.95751795e-06, 6.59654688e-05, 1.31811967e-05,
        1.72101622e-08, 3.96031828e-06],
       [2.76850812e-07, 4.77848212e-11, 3.41779071e-07, 2.10843965e-08,
        9.98905420e-01, 1.98133151e-07, 4.51479764e-07, 1.23897680e-05,
        2.74822355e-07, 1.08054548e-03]], dtype=float32)>